# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 225a74030bca324aaace51259b0c3d0b46f14b31d8e32a1594dbb0b3e2c62cb174909526fed8549677476e52e63cf8e8aa5a46befe62c3410588840bc5c9766a

test:
  secret_key_base: 188752a20f8e81b2b6489badace0ae616f791e457c3e8a25bd32ec0c556ee116d3783d5da5528ddfc6232ea2631923de1e3746c3be01f1f6aec77ac4313e5254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
