Given(/^the user is sign in$/) do                                                                                                                                                                                                             
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^the user visits the index page$/) do                                                                                                                                                                                                   
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Then(/^the user should see "(.*?)"$/) do |arg1|                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^the user signs out$/) do                                                                                                                                                                                                               
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
Given(/^the user is signed in$/) do                                                                                                                                                                                                           
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
When(/^the user fails to sign out$/) do                                                                                                                                                                                                       
  pending # express the regexp above with the code you wish you had                                                                                                                                                                           
end